### ISSUE TITLE
Incorrect ServiceControl & ServiceMonitor URLs sent to client vs configured

### ISSUE THREAD

**Issue by BadLiveware** [Particular/ServicePulse#2030]
#### Description
The ServiceControl and Monitoring URLs from app.constants.js are entirely different from those supplied by configuration, which results in a broken first experience

#### Expected behavior
ServicePulse should return the same URLs as configured

#### Actual behavior
Returns default relative paths
```js
❯ curl 'https://servicepulse.dev-ops.example.org/js/app.constants.js'
window.defaultConfig = {
  default_route: '/dashboard',
  version: '1.41.0',
  service_control_url: '/api/',
  monitoring_urls: ['/monitoring-api/'],
  showPendingRetry: true,
}
```
#### Versions
Servicepulse: 1.41.0
Servicecontrol: 5.7.0

Please list the version of the relevant packages or applications in which the bug exists.        
Running on GKE using nginx ingress

### Steps to reproduce

```yaml
❯ kubectl get cm -oyaml nservicebus
apiVersion: v1
data:
  ConnectionString: xyz
  DEFAULT_ROUTE: /dashboard
  MONITORING_URL: https://servicecontrol-monitoring.dev-ops.example.org
  SERVICECONTROL_URL: https://servicecontrol.dev-ops.example.org
  SHOW_PENDING_RETRY: "true"
  TransportType: RabbitMQ.QuorumConventionalRouting
kind: ConfigMap
metadata:
  name: nservicebus
  namespace: dev-ops-nservicebus
```

```yaml
❯ kubectl get deploy -oyaml servicepulse | yq '.spec.template.spec.containers[].env'
- name: TZ
  value: Europe/Stockholm
- name: SERVICECONTROL_URL
  valueFrom:
    configMapKeyRef:
      key: SERVICECONTROL_URL
      name: nservicebus
- name: MONITORING_URL
  valueFrom:
    configMapKeyRef:
      key: MONITORING_URL
      name: nservicebus
- name: DEFAULT_ROUTE
  valueFrom:
    configMapKeyRef:
      key: DEFAULT_ROUTE
      name: nservicebus
- name: SHOW_PENDING_RETRY
  valueFrom:
    configMapKeyRef:
      key: SHOW_PENDING_RETRY
      name: nservicebus
```

```yaml
❯ kubectl get ing nservicebus -oyaml | yq '.spec.rules[]'
host: servicepulse.dev-ops.example.org
http:
  paths:
    - backend:
        service:
          name: servicepulse
          port:
            number: 80
      path: /
      pathType: Prefix
host: servicecontrol.dev-ops.example.org
http:
  paths:
    - backend:
        service:
          name: servicecontrol
          port:
            number: 80
      path: /
      pathType: Prefix
host: servicecontrol-monitoring.dev-ops.example.org
http:
  paths:
    - backend:
        service:
          name: monitoring
          port:
            number: 80
      path: /
      pathType: Prefix
```

Outcome 
![image](https://github.com/user-attachments/assets/8c7004b2-dc64-43a4-b6de-87279afd1b6b)

### Relevant log output
-
