### ISSUE TITLE
First text column on dashboard should be truncated for long values

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#272]
First text column on the  dashboard should be truncated for long values. Currently large values mess up the grid.

The values should also not consist of multiple lines if they would contain CR/LF characters.

As a bonus the complete value could become visible when hovering (tooltip) or be shown in a details pane but the last costs space.

The truncation should be done with styling so that the truncation length is dependant on available space/resolution.

```css
.truncate {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
